package com.uom.cse.androidagent;

import android.content.Context;
import android.os.Bundle;
import android.os.Message;
import android.util.Log;

import com.espertech.esper.client.EventBean;
import com.espertech.esper.client.UpdateListener;
import com.uom.cse.androidagent.info.RAMUsageInfo;

/**
 * Asper compatible listener
 */

public class Listener implements UpdateListener
{
    // Listener identificator
    private String label;
    // Access counter
    private long access;

    private Context context;

    /**
     * Constructor
     * @param label
     */
    public Listener(String label,Context context)
    {

        this.label = label;
        this.context = context;
    }

    /**
     * Listener update method.
     * Retrives events generated by Asper
     * @param fresh
     * @param old
     */
    @Override
    public void update(EventBean[] fresh, EventBean[] old)
    {
        EventBean event = fresh[0];

        access++;
        Log.i("Asper Alert", "******************Desired event detected" + access);
        Message msgObj = MainActivity.handler.obtainMessage();
        Bundle b = new Bundle();
        String msg = "Summary of facebook last 1 min"+"\n";
        msg +=       "  Avg RAM usage - "+ event.get("avg_ram")+ "kB Avg CPU usage - " + event.get("avg_cpu") + "%\n";

        b.putString("message", msg);
        msgObj.setData(b);
        MainActivity.handler2.sendMessage(msgObj);
        //Toast.makeText(context, "*****Alert from Asper: Criricla event detected", Toast.LENGTH_LONG).show();

    }

    public String getLabel()
    {
        return label;
    }

    public long getAccess()
    {
        return access;
    }
}
